/* eslint-disable no-console */
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

/**
 * Deploys the AXIS AI protocol contracts in the correct order:
 *
 *   1. ValidatorRegistry(initialValidators)
 *   2. AXISToken(registry.address)         -> registry is the immutable minter
 *   3. registry.initializeToken(token)      -> one-time, permanent binding
 *   4. MarketplaceEscrow(token, registry)   -> marketplace settlement
 *
 * Initial validators come from INITIAL_VALIDATORS (comma-separated). If unset,
 * the deployer account is used as the sole bootstrap validator.
 *
 * The resulting addresses are written to ./deployments/<network>.json and to a
 * shared dotenv fragment so every other service can pick them up.
 */
async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network = hre.network.name;

  console.log(`Deploying AXIS AI protocol to network: ${network}`);
  console.log(`Deployer: ${deployer.address}`);

  const initialValidatorsEnv = process.env.INITIAL_VALIDATORS;
  const initialValidators = initialValidatorsEnv
    ? initialValidatorsEnv.split(",").map((a) => a.trim()).filter(Boolean)
    : [deployer.address];

  console.log("Initial validators:", initialValidators);

  // 1. ValidatorRegistry
  const Registry = await hre.ethers.getContractFactory("ValidatorRegistry");
  const registry = await Registry.deploy(initialValidators);
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log(`ValidatorRegistry deployed: ${registryAddress}`);

  // 2. AXISToken (registry is the only minter, immutable)
  const Token = await hre.ethers.getContractFactory("AXISToken");
  const token = await Token.deploy(registryAddress);
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();
  console.log(`AXISToken deployed: ${tokenAddress}`);

  // 3. Bind token to registry (one-time)
  const initTx = await registry.initializeToken(tokenAddress);
  await initTx.wait();
  console.log("Registry.initializeToken complete");

  // 4. MarketplaceEscrow
  const Escrow = await hre.ethers.getContractFactory("MarketplaceEscrow");
  const escrow = await Escrow.deploy(tokenAddress, registryAddress);
  await escrow.waitForDeployment();
  const escrowAddress = await escrow.getAddress();
  console.log(`MarketplaceEscrow deployed: ${escrowAddress}`);

  // Persist deployment artifacts.
  const deployment = {
    network,
    chainId: Number((await hre.ethers.provider.getNetwork()).chainId),
    deployer: deployer.address,
    initialValidators,
    contracts: {
      ValidatorRegistry: registryAddress,
      AXISToken: tokenAddress,
      MarketplaceEscrow: escrowAddress,
    },
    deployedAt: new Date().toISOString(),
  };

  const outDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(
    path.join(outDir, `${network}.json`),
    JSON.stringify(deployment, null, 2)
  );

  // Shared dotenv fragment consumed by start.sh / other services.
  const envFragment = [
    `# Auto-generated by contracts/scripts/deploy.js at ${deployment.deployedAt}`,
    `AXIS_TOKEN_ADDRESS=${tokenAddress}`,
    `VALIDATOR_REGISTRY_ADDRESS=${registryAddress}`,
    `MARKETPLACE_ESCROW_ADDRESS=${escrowAddress}`,
    `DEPLOY_CHAIN_ID=${deployment.chainId}`,
    "",
  ].join("\n");
  fs.writeFileSync(path.join(outDir, `${network}.env`), envFragment);

  console.log("\nDeployment complete. Addresses:");
  console.log(JSON.stringify(deployment.contracts, null, 2));
  console.log(`\nEnv fragment written to deployments/${network}.env`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
