packages:
  - "workers/*"

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - mppx
  - vocs
  - vite
  - waku
blockExoticSubdeps: true
strictDepBuilds: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
ignoredBuiltDependencies:
  - es5-ext
  - simple-git-hooks
allowBuilds:
  es5-ext: false
  esbuild: true
  sharp: true
  simple-git-hooks: false
  vue-demi: false
  workerd: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
